"""Add GroupMember model

Revision ID: 11c3d23a0158
Revises: 6eef72130c7f
Create Date: 2025-04-22 16:35:46.994369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c3d23a0158'
down_revision = '6eef72130c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('joined_msg_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_constraint('group_members_username_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['username'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_members_username_fkey', 'users', ['username'], ['username'])
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('joined_at')
        batch_op.drop_column('joined_msg_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
