"""init

Revision ID: 31f931b3031f
Revises: 0a1d83bb8b85
Create Date: 2025-04-12 09:02:05.190762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f931b3031f'
down_revision = '0a1d83bb8b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.String(length=80), nullable=True),
    sa.Column('to_user', sa.String(length=80), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    # ### end Alembic commands ###
