"""session‑and‑chat

Revision ID: 5cf9995c8bc5
Revises: 14e15afc3228
Create Date: 2025-04-11 11:27:45.829990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf9995c8bc5'
down_revision = '14e15afc3228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_token', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('current_device', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_device')
        batch_op.drop_column('current_token')

    # ### end Alembic commands ###
