"""init

Revision ID: 65da66298260
Revises: d4a92479ea31
Create Date: 2025-04-12 20:05:26.292290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65da66298260'
down_revision = 'd4a92479ea31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
