"""add group support

Revision ID: 871482203df7
Revises: 5e4bce45c846
Create Date: 2025-04-11 17:22:43.871135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871482203df7'
down_revision = '5e4bce45c846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('owner')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('messages_group_id_fkey', 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
