"""Initial migration

Revision ID: bf8de7cd4d21
Revises: 
Create Date: 2025-04-08 08:54:48.513957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8de7cd4d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_group_members')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('receiver', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender'], ['username'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['username'], ['username'])
        batch_op.drop_column('is_read')
        batch_op.drop_column('receiver')
        batch_op.drop_column('sender')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    op.create_table('_alembic_tmp_group_members',
    sa.Column('group_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('group_id', 'username')
    )
    # ### end Alembic commands ###
