"""init

Revision ID: d4a92479ea31
Revises: 3ee54821d904
Create Date: 2025-04-12 11:15:04.928455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a92479ea31'
down_revision = '3ee54821d904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
