"""sos system extension

Revision ID: fbd231ce094d
Revises: dd5561ca5fbb
Create Date: 2025-05-16 10:38:54.370604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd231ce094d'
down_revision = 'dd5561ca5fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sos_id', sa.Integer(), nullable=True),
    sa.Column('reporter', sa.String(length=80), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_danger', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rescuer', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))
        batch_op.drop_column('photo')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banned')
        batch_op.drop_column('rating')

    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('closed')
        batch_op.drop_column('rescuer')
        batch_op.drop_column('active')
        batch_op.drop_column('photos')
        batch_op.drop_column('is_danger')
        batch_op.drop_column('status')

    op.drop_table('sos_report')
    # ### end Alembic commands ###
